services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
    command: pnpm run start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres_data:
